### PR TITLE
docs(canvas): add support note for Braille marker

### PR DESCRIPTION
**Pull request by joshka**
Addresses https://github.com/ratatui-org/ratatui/issues/457

### CODE REVIEW

**Comment by joshka** [comment]
Pinging @relf for input

**Comment by Valentin271** [comment]
I wonder should we link to some fonts that support this? Otherwise LGTM.

**Review by orhun — APPROVED** [review]
+1

**Comment by relf** [comment]
The thing is, discovering `ratatui`, I just ran the demo and seing I did not get the right result out of the box, I started to dive into the code to find out, your additions would have definitely helped. 
That said, I've just noticed now (!) that I've skipped the warning just after in the [example section](https://github.com/ratatui-org/ratatui#examples) where you explain about having gliphs not showing up correctly 🤦‍♂️, maybe
some **bold font** could have helped (?) and/or links to "good" fonts would be nice right here.
The default configuration on Windows (Consolas font) does not work, I think this could be stressed as an example of "bad" configuration.
Anyway thanks and keep up the good work!

**Comment by kdheepak** [comment]
Should we also add a one line text description to the `ui` in the example for `chart.rs`?:

https://github.com/ratatui-org/ratatui/blob/0c68ebed4f63a595811006e0af221b11a83780cf/examples/chart.rs#L145

Something like "Requires terminal and font support for unicode".

**Comment by joshka** [comment]
> The default configuration on Windows (Consolas font) does not work, I think this could be stressed as an example of "bad" configuration.

I'd be more inclined to suggest that whatever we do with demos should generally look good out of the box for a default configuration, so perhaps we should switch to dots instead of braille for the main demo and introduce the braille markers later?

**Comment by Valentin271** [comment]
Yes this seems like a good idea to me.

**Comment by relf** [comment]
> demos should generally look good out of the box for a default configuration, so perhaps we should switch to dots instead of braille for the main demo and introduce the braille markers later

Yes that was my first thought but I did not dare to suggest it (more involved changes), but now that you say it...

**Comment by joshka** [comment]
> I wonder should we link to some fonts that support this? Otherwise LGTM.

Perhaps a wiki page might be appropriate for this?

**Pull request merged**
