### PR TITLE
docs(README.md): fix links to CONTRIBUTING.md and BREAKING-CHANGES.md

### PR DESCRIPTION
**Pull request by hueblu**
Fixes a problem in README.md where the links to CONTRBUTING.md and BREAKING-CHANGES.md wouldn't work.

### CODE REVIEW

**Comment by joshka** [comment]
Hey there @hueblu, thanks for the PR :)

**Review by joshka — APPROVED** [review]

**Comment by joshka** [comment]
Hey @hueblu would you mind setting up gpg and signing your commits? https://github.com/ratatui-org/ratatui/blob/main/CONTRIBUTING.md#sign-your-commits

**Comment by hueblu** [comment]
> Hey @hueblu would you mind setting up gpg and signing your commits? https://github.com/ratatui-org/ratatui/blob/main/CONTRIBUTING.md#sign-your-commits

Of course, sorry about that. 
Do i have to redo the pr or is it fine?

**Comment by joshka** [comment]
No problem. I see you closed the PR, but to make it easier for you next time, you can also update a PR by force pushing a change to the existing branch which will automatically update the PR with your changes.

**Pull request closed without merging**
