### PR TITLE
chore: deprecate Buffer::get and get_mut

### PR DESCRIPTION
**Pull request by joshka**
Fixes: https://github.com/ratatui-org/ratatui/issues/1122

### CODE REVIEW

**Comment by EdJoPaTo** [comment]
Probably superseded by #1084?

**Comment by joshka** [comment]
> Probably superseded by #1084?

Yeah, unless we want to split the two for easier review.

**Comment by EdJoPaTo** [comment]
Its only a `#[deprecated]` more, so not a huge difference on reviewing. The bigger question… do we want to deprecate directly? As this PR exists it seems to be something that was considered not to do at first?

Personally I think the Index trait is an exact replacement of the current get methods and the cell methods provide the new ones so it's only better than before with exact replacements. It would be better to include the deprecation to have a consistent usage.

**Comment by joshka** [comment]
This is not about whether the deprecation happens, it's about whether it happens in the same PR as the other changes.

The reason for splitting this PR is for review purposes. Large PRs are more difficult to review, and cause problems when there are merges, more features changed, rebases, etc. The cognitive load required to review, and the amount of time necessary to dedicate to just opening a larger PR is usually much larger. Smaller amounts of work are generally easier to get over the line in a reasonable time, and this time scales in a non-linear manner with the PR size.

**Comment by joshka** [comment]
Merged in #1084

**Pull request closed without merging**
