### PR TITLE
feat(table): accept Text for highlight_symbol

### PR DESCRIPTION
**Pull request by joshka**
This allows for multi-line symbols to be used as the highlight symbol.

```rust
let table = Table::new(rows, widths)
    .highlight_symbol(Text::from(vec![
        "".into(),
        " █ ".into(),
        " █ ".into(),
        "".into(),
    ]));
```

  Made with VHS

### CODE REVIEW

**Review by kdheepak — APPROVED** [review]
This looks good to me!

**Review by Valentin271 — APPROVED** [review]

**Comment by kdheepak** [comment]
tests are failing on the `main` branch

```
error[E0308]: mismatched types
   --> src/widgets/table/table.rs:835:44
    |
835 |         assert_eq!(table.highlight_symbol, None);
    |                                            ^^^^ expected `Text<'_>`, found `Option<_>`
    |
    = note: expected struct `text::text::Text<'_>`
                 found enum `std::option::Option<_>`

error[E0308]: mismatched types
   --> src/widgets/table/table.rs:851:44
    |
851 |         assert_eq!(table.highlight_symbol, None);
    |                                            ^^^^ expected `Text<'_>`, found `Option<_>`
    |
    = note: expected struct `text::text::Text<'_>`
                 found enum `std::option::Option<_>`
```

**Comment by Valentin271** [comment]
Oops my bad :sweat_smile:

**Comment by joshka** [comment]
> Oops my bad 😅

Definitely mine :D

**Pull request merged**
