### PR TITLE
feat(chart): add GraphType::Bar

### PR DESCRIPTION
**Pull request by joshka**
Demo

### CODE REVIEW

**Comment by joshka** [comment]
Inspired by btop, it might be nice to be able to have graphs that can be bar charts and not just lines / scatter.
image

**Comment by joshka** [comment]
@ratatui-org/maintainers review-plz. This is a pretty small easy feature to approve.

**Review by kdheepak — APPROVED** [review]

**Comment by EdJoPaTo** [comment]
We should get #1166 merged…

```plaintext
$ cargo semver-checks
     Parsing ratatui v0.27.0 (current)
      Parsed [  20.007s] (current)
     Parsing ratatui v0.27.0 (baseline)
      Parsed [  18.716s] (baseline)
    Checking ratatui v0.27.0 -> v0.27.0 (no change)
     Checked [   0.110s] 76 checks: 75 pass, 1 fail, 0 warn, 0 skip

--- failure enum_variant_added: enum variant added on exhaustive enum ---

Description:
A publicly-visible enum without #[non_exhaustive] has a new variant.
        ref: https://doc.rust-lang.org/cargo/reference/semver.html#enum-variant-new
       impl: https://github.com/obi1kenobi/cargo-semver-checks/tree/v0.33.0/src/lints/enum_variant_added.ron

Failed in:
  variant GraphType:Bar in …/ratatui/src/widgets/chart.rs:155
```

**Comment by joshka** [comment]
Yeah, I think we actually need to mark a bunch of places as non-exhaustive like this where we might reasonably expect to add fields.

**Pull request merged**
