### PR TITLE
feat: Add `Color::from_hsl` ✨

### PR DESCRIPTION
**Pull request by kdheepak**
This PR adds `Color::from_hsl` that returns a valid `Color::Rgb`. 

```rust
let color: Color = Color::from_hsl(360.0, 100.0, 100.0);
assert_eq!(color, Color::Rgb(255, 255, 255));

let color: Color = Color::from_hsl(0.0, 0.0, 0.0);
assert_eq!(color, Color::Rgb(0, 0, 0));
```

HSL stands for Hue (0-360 deg), Saturation (0-100%), and Lightness (0-100%) and working with HSL the values can be more intuitive. For example, if you want to make a red color more orange, you can change the Hue closer toward yellow on the color wheel (i.e. increase the Hue).

Related #763

### CODE REVIEW

**Comment by joshka** [comment]
Can we import an optional library for this functionality instead?

**Review by orhun — APPROVED** [review]

**Comment by orhun** [comment]
I think the logic/conversion is pretty simple and it does not pose a huge maintenance burden (and it is not going to change anytime soon - `hsl-rs` was updated 5 years ago). On the other hand, if there are more benefits to using an optional library (such as more functionality / faster code) then I'm up for it.

**Comment by kdheepak** [comment]
If we import a library like https://crates.io/crates/palette we can convert from any color space to RGB and it would be worth it in my opinion. HSLuv is the main one that people recommend for perceptually uniform color spaces.

https://www.hsluv.org/comparison/

If we are only going to stick to HSL, I agree with @orhun, this implementation is standard and there's little to no maintenance cost.

**Comment by joshka** [comment]
Are we just going to stick with HSL? Why that over HSV or some other approach?

**Comment by kdheepak** [comment]
My guess for why HSL is more popular than HSB/HSV is that in HSB, 100% Brightness/Value gives you the white color only when the Saturation is 0. But in HSL, 100% Lightness will give you white independent of the value of Saturation.

So HSL is more intuitive, since you can increase Lightness to get closer to white and decrease Lightness to get closer to black. With HSB/HSV you have to change two things, and in opposite directions.

**Comment by joshka** [comment]
I guess my point is that there are already so many versions of this sort of function in various crates:
- https://docs.rs/sorbet-color/0.3.1/sorbet_color/
- https://crates.io/crates/colortypes
- https://crates.io/crates/palette
- etc.

No problem with merging this as-is though.

**Comment by joshka** [comment]
- https://crates.io/crates/colorsys/ seems to have a pretty decent API

**Comment by kdheepak** [comment]
I don't see people needing to use cmyk (because it is primarily used for print and not digital). Also, for terminals, the `alpha` property is pointless. 

imo only `HSL` and `HSLuv` (and maybe other equivalent perceptually uniform) color spaces are probably the most useful to have in the library.

**Comment by joshka** [comment]
Makes sense.

**Pull request merged**
