### PR TITLE
ci: put commit id first in changelog

### PR DESCRIPTION
**Pull request by joshka**
```shell
git cliff --unreleased
```
[CHANGELOG.md](https://github.com/ratatui-org/ratatui/files/12503810/CHANGELOG.md)

image

### CODE REVIEW

**Comment by orhun** [comment]
How do you think this helps with readability? I think the current format is good and I would say let's stick to it for a while for consistency in the changelog :D

**Comment by joshka** [comment]
Mostly this is a cosmetic change backed by some subjective preferences.

Putting the commit ID first makes the visual design hierarchy more obvious by implying that each row in the changelog is strongly coupled with a commit. It also avoids the subjective messiness of having two parenthesized parts at the end of line (and avoids wrapping the commit id to the next line. By putting a fixed size piece of text at the beginning of a line, it allows someone reading to more easily ignore the first part when scanning down a list of items than if the same blue text is at the end of the line or on the following line. It's not a massive deal either way, but I think this is marginally nicer.

Current Changelog for comparison:

image

**Comment by mindoodoo** [comment]
@joshka Is the commit ID always wrapped to the next line as in your screenshot ?

**Comment by joshka** [comment]
> @joshka Is the commit ID always wrapped to the next line as in your screenshot ?

No - sorry. I'd pasted the output of git-cliff into a github comment and that renders this wrong. My mistake there.

**Review by mindoodoo — APPROVED** [review]
Aight, I guess I'm good either way, though I agree with orhun that we shouldn't change it up too often.

The change makes sense and will put an even stronger emphasis on writing clean commits.

**Review by orhun — APPROVED** [review]

**Pull request merged**
