### PR TITLE
fix: MouseEvent for table for scrolling

### PR DESCRIPTION
**Pull request by Mehrbod2002**
fixes: #173   

and also able to set style in right side of table widget and BG color and use it up and down with it on ScrollEvent , but not sure how to grab it up and down . supposed grab an item done before in this crate and hope developers guide me if the attention of issue was this .

### CODE REVIEW

**Comment by joshka** [comment]
Hiya, thanks for raising this PR. We appreciate all contributions and I hope that I can encourage you to continue doing so even though I'm pushing back against this specific PR.

This PR adds crossterm event reading (if the crossterm feature is enabled) into the render method of the table widget. This is something that no other widgets in the library do so far, so it's a bit of a new idea. I think there's probably a bunch of problems that come from it. The first one I can see is that the read() call is blocking, which would mean that if no mouse events are coming, then this blocks all future renders.

Another issue is that this would mean that there is only a single scroll target for an entire application.

One big thing that should be considered is that applications written with ratatui are currently able to handle their own events etc. with whatever method is appropriate for the app (e.g. I have an app that does this with non blocking event streams, joined with other event sources, and which bubbles events to various widgets based on which is currently visible).

So, while I welcome this idea, I need to suggest that talking through the design of this needs to happen before a PR.

For some notes and discussion about scrolling approaches generally, see Take a look at https://github.com/tui-rs-revival/ratatui/issues/174. It's a work in progress, and would be great to hear some feedback on.

**Comment by Mehrbod2002** [comment]
@joshka So it should be a State for scroll which is upper state and scrollbar to drag .
even I can't understand how it will possible on this idea as core code events all defined on loop and not in core .

**Comment by joshka** [comment]
> @joshka So it should be a State for scroll which is upper state and scrollbar to drag . even I can't understand how it will possible on this idea as core code events all defined on loop and not in core .

I'm having some difficulty understanding what you're saying. If English is your second language, can you write a response in your own language and ask ChatGPT to translate it for you?

The app loop is code that users of this library write themselves. We don't provide the loop (except in a sample app). Each app can write that loop differently. E.g. some might render every 250ms, some others might only ever call render when there is a new event that changes the application's state.

The render function of a widget should not block waiting for a crossterm event. Blocking will prevent other events causing a render. To see this problem, run `cargo run --example table`. You will not see any output until you move the mouse. This is a problem.

The second problem is what to do when there are two tables. The application should make a choice about how to handle that. We can't make that choice in this library.

Therefore the mouse event handling needs to be outside of the widget, not part of the widget.

**Comment by orhun** [comment]
Closing due to inactivity.

**Pull request closed without merging**
