### PR TITLE
chore: Updated Layout in tabs.rs example

### PR DESCRIPTION
**Pull request by Libroru**
I updated the tabs.rs example to use the new syntax for tabs.
Other examples might need to be changed as well.

### CODE REVIEW

**Comment by kdheepak** [comment]
This PR changes it from the new to the old syntax. Can you clarify where you read about this? If anything has to be changed to the new syntax, it is probably our documentation on the website.

**Comment by joshka** [comment]
> If anything has to be changed to the new syntax, it is probably our documentation on the website.

Ah, that would make sense. I didn't think about how this sort of thing would affect users when updating the examples. Oops.

**Comment by Libroru** [comment]
> This PR changes it from the new to the old syntax. Can you clarify where you read about this? If anything has to be changed to the new syntax, it is probably our documentation on the website.

That's how I got it working in my personal projects with version `0.25.0`. But yeah in addition to that the documentation [also shows the old syntax](https://docs.rs/ratatui/latest/ratatui/layout/struct.Layout.html#example). I figured that that would be the new syntax since it worked on a local installation of `0.25.0`.

**Comment by joshka** [comment]
I'm going to close this PR out, and move it to an issue instead.

**Comment by joshka** [comment]
See https://github.com/ratatui-org/ratatui/issues/779

**Pull request closed without merging**
