### PR TITLE
fix: useless allocations creating Line

### PR DESCRIPTION
**Pull request by SUPERCILEX**
Seems like the fact that a Cow is passed in was forgotten.

### CODE REVIEW

**Comment by SUPERCILEX** [comment]
I don't understand why clippy is yelling at me as none of the changes are related.

**Comment by joshka** [comment]
> I don't understand why clippy is yelling at me as none of the changes are related.

Likely rust release day clippy lint changes :) I've been meaning to add a workflow that tests using nightly to find this sort of thing early. Will fix as another PR.

**Comment by SUPERCILEX** [comment]
Oh right 1.80! Well sounds good, lemme know when I should pull.

**Comment by joshka** [comment]
https://github.com/ratatui-org/ratatui/pull/1238 has the clippy fixes and is merged

**Review by orhun — APPROVED** [review]

**Comment by SUPERCILEX** [comment]
Yay, thanks!

**Comment by joshka** [comment]
Thanks for the PR :)

**Pull request merged**
