### PR TITLE
feat: implement Lender for WordWrapper and LineTruncator

### PR DESCRIPTION
**Pull request by progval**
As a convenience for users of ratatui, as the [lender](https://crates.io/crates/lender) crate implements plenty of Iterator-like methods.

No test because this does not really add any new code.

This includes a commit from #608 in order to avoid merge conflicts

### CODE REVIEW

**Comment by progval** [comment]
Here is an example of how Lender could be used: https://github.com/ratatui-org/ratatui/commit/3fa1b91a387f62ad54b1f4323aaabef1c2e51b68 (this depends on #610 because a trait object can't implement two traits, namely `Lender` and `Lending`)

**Comment by joshka** [comment]
Can you explain the problem here? It's not clear.

(Also - we'd prefer to not add more complexity to reflow instead replace it - see https://github.com/ratatui-org/ratatui/issues/293 for details)

**Comment by progval** [comment]
It's not really a problem, `Lender` just avoids the need to reimplement iterator-like behavior in callers. For example, here is how I have to change my code if `WordWrapper` didn't implement `Lender`:

```diff
diff --git a/src/widgets/bottom_aligned_paragraph.rs b/src/widgets/bottom_aligned_paragraph.rs
index 85f957f..0726602 100644
--- a/src/widgets/bottom_aligned_paragraph.rs
+++ b/src/widgets/bottom_aligned_paragraph.rs
@@ -14,10 +14,9 @@
  * along with this program.  If not, see <https://www.gnu.org/licenses/>.
  */
 
-use lender::{Lender, Lending};
 use ratatui::prelude::*;
 use ratatui::text::StyledGrapheme;
-use ratatui::widgets::reflow::WordWrapper;
+use ratatui::widgets::reflow::{LineComposer, WordWrapper};
 use unicode_width::UnicodeWidthStr;
 
 use super::OverlappableWidget;
@@ -54,7 +53,7 @@ impl<'a> OverlappableWidget for BottomAlignedParagraph<'a> {
     // Inspired by https://github.com/ratatui-org/ratatui/blob/9f371000968044e09545d66068c4ed4ea4b35d8a/src/widgets/paragraph.rs#L214-L275
     let trim = false;
     let style = Style::default();
-    let lines: Vec<_> = WordWrapper::new(
+    let mut wrapper = WordWrapper::new(
       self.text.lines.iter().map(|line| {
         (
           line
@@ -66,10 +65,16 @@ impl<'a> OverlappableWidget for BottomAlignedParagraph<'a> {
       }),
       area.width,
       trim,
-    )
-    .skip(self.scroll as usize)
-    .map_into_iter(|line: ratatui::widgets::reflow::WrappedLine| line.line.to_vec())
-    .collect();
+    );
+    for y in 0..self.scroll {
+      if wrapper.next_line().is_none() {
+        break;
+      }
+    }
+    let mut lines = Vec::new();
+    while let Some(line) = wrapper.next_line() {
+      lines.push(line.line.to_vec());
+    }
     let text_area = area; // Borders not supported by BottomAlignedParagraph (yet?)
     let text_area_height = text_area.height as usize;
     let lines = if lines.len() > text_area_height {
```

**Comment by progval** [comment]
closing, given that I copied the code to my crate instead (https://github.com/ratatui-org/ratatui/pull/607#issuecomment-1791647074). Feel free to reuse it if you want it in the future, though

**Pull request closed without merging**
