### PR TITLE
feat: adds centered to public API

### PR DESCRIPTION
**Pull request by wookietreiber**
I'm leaving this in draft for now and won't be adding tests or fixing coverage just yet. Wanted to communicate my idea for #617. If you want this to happen, let me know, then I'll add tests for coverage, etc. 

I think the function name should be changed to something that reads better. Haven't come up with any good ideas though :thinking: 

---

fixes #617

### CODE REVIEW

**Comment by kdheepak** [comment]
Thanks for the PR! I also tend to have this in almost every application, and I believe this is a good candidate for inclusion. 

There is already a `inner` method:

https://github.com/ratatui-org/ratatui/blob/59b9c32fbc2bc6725bdec42e63216024fab71493/src/layout/rect.rs#L93

That people can use like this:

```rust
Rect::new(1, 2, 3, 4).inner(&Margin::new(1, 2)),
```

I'm not sure if this can be done in a non-breaking manner, but it would have been nice to use the same function for different purposes.

e.g.


```rust
Rect::new(1, 1, 10, 10).inner(Margin::px(1, 2))
Rect::new(1, 1, 10, 10).inner(Margin::percent(10, 20))
```

**Comment by joshka** [comment]
Definitely something more generic than this would be preferable. I'm not sure exactly how the API would look, perhaps using `Constraint`s for specifying things? Let's chat on that in #617

**Comment by joshka** [comment]
See notes in #617 about using flex instead of this approach.

**Comment by joshka** [comment]
Given that this is too specific (i.e. it only deals with creating a rectangle that is a certain percentage high / wide, and not a rectangle with any other constraints, nor multiple rectangles), I'm going to close this out. Thank you for the PR even if we didn't merge it.

The replacement code for this is effectively the following, which clearly expresses the intended effect.
```rust
let [area] = Layout::horizontal([Constraint::Percentage(50)]).flex(Flex::Center).areas(area);
let [area] = Layout::vertical([Constraint::Percentage(20)]).flex(Flex::Center).areas(area);
```

The only part that is really missing here is a neat syntax for working in two dimensions at once in a single statement. This seems like an orthogonal (pun intended) concern to this PR.

I'll update https://ratatui.rs/recipes/layout/center-a-rect/ shortly.

**Comment by wookietreiber** [comment]
Sorry about not responding sooner, thanks for keeping up with this :+1:

**Comment by joshka** [comment]
No problem :)

**Pull request closed without merging**
