### PR TITLE
docs(examples): update table gif

### PR DESCRIPTION
**Pull request by Emivvvvv**
Issue: https://github.com/ratatui-org/ratatui/issues/800

New gif from the new table example https://github.com/ratatui-org/ratatui/pull/840

### CODE REVIEW

**Comment by Emivvvvv** [comment]
Screenshot 2024-01-17 at 23 49 34

There was a empthy line in the first version. Fixed it by changing the height value of the table.tape

**Comment by Emivvvvv** [comment]
Hmm, and now the scrollbar is not filling all of the rows. It's up to you to choose which one is better.

**Comment by joshka** [comment]
Let's get #840 completed before we update this. Marking as draft until then.

**Comment by Emivvvvv** [comment]
Updated version
table

**Review by joshka — APPROVED** [review]

**Pull request merged**
