### PR TITLE
refactor(example): add scroll to flex example

### PR DESCRIPTION
**Pull request by Valentin271**
On a standard size terminal, flex example is cut off which is a shame because of how great it is.

image

I added scroll to the example.

`constraints` will also need that but I first want to validate this kind of janky implementation.

### CODE REVIEW

**Comment by kdheepak** [comment]
Neat hack!

**Comment by Valentin271** [comment]
> Neat hack!

It was easier than refactoring the example to draw offset and all ...

I think something similar could be added to `Buffer` itself.

**Comment by kdheepak** [comment]
I moved the name of the constraints into the box itself (thanks for @joshka for the idea) and changed the scrolling to make it never go past the last example.

default:

image

max scroll:

image

I also changed some of the constraints such that it shows how flex behaves even with just 80 px width (and shows the name of the constraints well).

**Comment by Valentin271** [comment]
Looks great!

I tweak it a bit more:

- replaced example height value with a constant to avoid desync and be self documenting
- replaced `clamp(0, ...)` with `min(...)`
- Increased `Length(10)` to 12 so it's not truncated as below

image

**Comment by kdheepak** [comment]
I was making almost the exact same changes lol 

image

Pushing mine now

**Comment by kdheepak** [comment]
Previously colors were just incremented in order to match a title. With the title moved into the blocks, we don't need that.

Now, I made the colors dependent on the type of constraint:

image

I think this makes it easier to visually parse what is going on.

**Review by kdheepak — APPROVED** [review]

**Review by kdheepak — APPROVED** [review]

**Comment by kdheepak** [comment]
I'm going to add a couple more examples here, now that scroll is implemented, we can show more behavior.

**Comment by kdheepak** [comment]
This is good to go imo.

**Comment by kdheepak** [comment]
Here's a demo of it as a gif. I'm adding the tape file to this PR as well.

flex

**Comment by kdheepak** [comment]
here's the latest gif 

flex

**Pull request merged**
