### PR TITLE
docs: remove simple-tui-rs

### PR DESCRIPTION
**Pull request by joshka**
This has not been recently and doesn't lead to good code

### CODE REVIEW

**Comment by orhun** [comment]
ping @pmsanford

**Comment by joshka** [comment]
The context on this is that a user in discord mentioned they were using this repo as a base because it seemed like the right idea. It may have been way back when tui-rs was just a young project, but it's got a few things would be better not to use in a newer project.
- Termion
- `Spans` instead of `Line`
- etc.

**Comment by pmsanford** [comment]
Thanks for the ping; I'd be happy to update it, but I can't make any commitments on a timeline at the moment. I'd suggest going ahead with merging this PR and when/if I get it updated I'll open one to re-add it. I'll also add a note to my repo saying it's not up to date and link to this PR.

**Comment by orhun** [comment]
Sounds good, thank you!

**Review by orhun — APPROVED** [review]

**Pull request merged**
