### PR TITLE
chore: Add a check for if breaking change label should be added 

### PR DESCRIPTION
**Pull request by kdheepak**
This PR will do 3 things

1. Add a comment if the title is not in conventional commit specification, urging the PR submitter to change it
2. Remove the comment if the title is updated
3. Add a `breaking change` label if the title has a `!:` in it and follows the conventional commit specification.

### CODE REVIEW

**Review by joshka — APPROVED** [review]
Neat

**Comment by orhun** [comment]
Hey, I'm curious how did you test this? Is there an example PR at somewhere else?

**Comment by kdheepak** [comment]
Here's where I tested it: https://github.com/ratatui-org/ratatui/pull/482. If you want to try it you can restore branch and reopen the PR. I also have a personal repo where I did tests that I can share if you'd like.

**Comment by orhun** [comment]
Got it, thanks for sharing!

**Pull request merged**
