### PR TITLE
docs(examples): add descriptions and update theme

### PR DESCRIPTION
**Pull request by joshka**
Fixes https://github.com/ratatui-org/ratatui/issues/401

- docs(examples): add descriptions and update theme
Use the OceanicMaterial consistently in examples

- docs(examples): move example gifs to github
A new orphan branch named "images" is created to store the example images

See https://github.com/ratatui-org/ratatui/tree/images

### CODE REVIEW

**Review by orhun — APPROVED** [review]
LGTM, should we also auto-generate GIFs on that branch?

**Comment by joshka** [comment]
Definitely worth doing sometime, but there doesn't seem to be an easy way to only generate the gif that has changed, so manual works for the short term.

**Comment by orhun** [comment]
Uhm, why this was closed?

**Comment by joshka** [comment]
We were modifying the merge settings at the time (as rebasing doesn't work with signed commits), and I merged this manually (so the two commits would be separate rather than squashed).
Just https://github.com/joshka/ratatui/commit/ca9bcd3156f55cd2df4edf003aa1401abbed9b12 and https://github.com/joshka/ratatui/commit/5c785b22709fb64a0982722e4f6d0021ccf621b2 are merged (not the extraneous https://github.com/ratatui-org/ratatui/pull/460/commits/bb14d77bcd79fecb9019c392b8d981438e08d682)

**Pull request closed without merging**
