### PR TITLE
style: remove spacing for tabs

### PR DESCRIPTION
**Pull request by bhavuk2002**
#502 

updated the tabs widget as specified in the issue, updated for divider and removed spaces before the tabs, tell me if any further changes required.

### CODE REVIEW

**Comment by bhavuk2002** [comment]
can someone please explain these check?

**Comment by Chocorean** [comment]
`Continuous Integration / lint (pull_request)` failed because your commit message has to start with the name of the task you've done, here's a few examples:

- **docs:** import prelude::* in doc examples
- **chore:** only run check pr action on pull_request_target events

List of available tasks [here](https://github.com/ratatui-org/ratatui/actions/runs/6200526919/job/16835391136?pr=506#step:9:52) ; I guess changing the name of the PR is not enough! 

`Continuous Integration / coverage (pull_request)` failed because it seems [some tests failed](https://github.com/ratatui-org/ratatui/actions/runs/6200526919/job/16835390741?pr=506#step:5:633)

**Comment by joshka** [comment]
Just to close the loop on this - this PR needs to hold off a minute before some feedback on https://github.com/ratatui-org/ratatui/issues/502 is resolved. I want the change, and the change is probably relatively simple but there are a couple of approaches.

**Comment by bhavuk2002** [comment]
What does that mean? PR need to hold for a minute before feedback?

**Comment by joshka** [comment]
I was noting the reason for not reviewing this yet. It's not because of any problem with the code etc. It's because the issue wasn't yet ready to implement. I was making sure that the conversation in https://github.com/ratatui-org/ratatui/issues/502#issuecomment-1722124429 was clearly communicated (closing the loop).

If this is the alternative that is chosen, I'd be happy to ping you to complete this PR, but I don't want to waste your time with addressing code issues before the design approach is certain.

**Comment by bhavuk2002** [comment]
Ya you are right.

**Comment by joshka** [comment]
Another person is working on https://github.com/ratatui-org/ratatui/pull/629 which fixes this in a way that works better. Closing this out for now. Thank you for submitting this PR and I do hope you will consider doing so in the future too.

**Pull request closed without merging**
