### PR TITLE
build(deps): upgrade crossterm to 0.27

### PR DESCRIPTION
**Pull request by a-kenji**
[Changelog](https://github.com/crossterm-rs/crossterm/blob/master/CHANGELOG.md#version-027)

Upgrade `crossterm` to `v0.27`.

I don't think this is a breaking change, since the `crossterm` internals aren't exposed, is that correct?

### CODE REVIEW

**Comment by sayanarijit** [comment]
IMO it is a breaking change because ratatui requires us to install crossterm separately for input handling. Some extensions will break too.

**Comment by a-kenji** [comment]
You should be able to have `ratatui` with `0.27` and a separate `crossterm` for handling input events that is on `0.26`.

And there shouldn't be conflicting dependencies since `ratatui` is not using the `event` feature.

Can you show me an example of an extension that will break as a result of this change? 

I am happy to mark this as a breaking change if that is the consensus.

**Comment by joshka** [comment]
What should we do about doc comments / readme for this? Make the change now or leave it until we release? I wonder how many people use the version number from the github readme.

**Comment by sayanarijit** [comment]
Cool... I have tested with [tui-input](https://github.com/sayanarijit/tui-input). After a `cargo update`, works fine.

**Review by sayanarijit — APPROVED** [review]

**Review by joshka — APPROVED** [review]

**Pull request merged**
