### PR TITLE
feat: expand serde attributes for `TestBuffer`

### PR DESCRIPTION
**Pull request by a-kenji**
This makes it possible to deserialize/serialize the whole test buffer with the `serde` feature.

### CODE REVIEW

**Comment by joshka** [comment]
I'm curious what you're using this for.

Do you think this needs unit / integ tests? It would help catch any serialization breaking changes if these were tested.

**Comment by a-kenji** [comment]
I am not quite sure how to test the serialization without bringing in another dependency. I will look further into it.


I am in the process of prototyping a snapshot testing helper, specifically for ratatui.
Which should be capable of rendering exactly what ratatui is able to render, to make testing styles and modifiers easier and maybe even color themes.
[serde_ratatui.webm](https://github.com/ratatui-org/ratatui/assets/65275785/f94b2a5e-7b25-4a9e-ac2f-a7a5ed47a7f7)

**Comment by joshka** [comment]
>I am in the process of prototyping a snapshot testing helper, specifically for ratatui.
Which should be capable of rendering exactly what ratatui is able to render, to make testing styles and modifiers easier and maybe even color themes.

Cool stuff!

**Review by joshka — APPROVED** [review]
No big deal on the tests for this - unless there's a simple way to do this. None of our other serializable types have tests right now.

**Comment by joshka** [comment]
Needs to be rebased before merging. Can you please take a look?

**Review by joshka — APPROVED** [review]

**Pull request merged**
