### PR TITLE
feat(span): implement Widget on Span

### PR DESCRIPTION
**Pull request by joshka**
This allows us to use Span as a child of other widgets, and to use
Span::render() to render it rather than calling buffer.set_span().

```rust
frame.render_widget(Span::raw("Hello, world!"), area);
// or
Span::raw("Hello, world!").render(frame, area);
// or even
"Hello, world!".green().render(frame, area);
```

### CODE REVIEW

**Comment by joshka** [comment]
`Line` will get the same next (once https://github.com/ratatui-org/ratatui/pull/708 is merged)

The end goal of this is to fully remove the `Buffer::set_line` and `Buffer::set_span` methods, and implement various alignment type things in the line itself instead of in other widgets (like block title, various chart labels etc.).

**Review by Valentin271 — APPROVED** [review]
Seems like a good idea, approved

**Review by orhun — APPROVED** [review]

**Comment by kdheepak** [comment]
Should we also implement `Widget` on `&str`? i.e. `"Hello, world!".render(frame, area);`

**Comment by joshka** [comment]
That might be a little too magical for my taste

**Comment by kdheepak** [comment]
If I have code that is like `"Hello, world!".green().render(frame, area);` and I want to remove the color, how would you recommend I do it?

**Comment by joshka** [comment]
I see your point there. `.into::<Span>()` might work?

**Pull request merged**
