### PR TITLE
chore(github): add EdJoPaTo as a maintainer

### PR DESCRIPTION
**Pull request by orhun**
@EdJoPaTo 🧀

### CODE REVIEW

**Review by EdJoPaTo — APPROVED** [review]
:cheese:

**Review by EdJoPaTo — COMMENTED** [review]
Can they be places on individual lines?

Maybe sort them alphabetically? Then I would be first… Don't sort them alphabetically! :P

**Comment by orhun** [comment]
> Can they be places on individual lines?

Nope, it didn't work before #236

**Review by kdheepak — APPROVED** [review]

**Comment by orhun** [comment]
@EdJoPaTo feel free to merge whenever you're ready for duty! 🫡

**Pull request merged**
